// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWHDxXY4vHvlQ2Rx5BgiHKP74BBuNN4U',
    appId: '1:795386471482:web:1cd7211e57eb7e7705c103',
    messagingSenderId: '795386471482',
    projectId: 'chat-gemini-5a384',
    authDomain: 'chat-gemini-5a384.firebaseapp.com',
    storageBucket: 'chat-gemini-5a384.appspot.com',
    measurementId: 'G-GEBE3P4936',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd1z9rbhy7NpkMxvlx6usJ6UabJIqfxNc',
    appId: '1:795386471482:android:ab443e80a7c1c6e305c103',
    messagingSenderId: '795386471482',
    projectId: 'chat-gemini-5a384',
    storageBucket: 'chat-gemini-5a384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFn67MvLxSooOVajwhlgia-faT6xh6x7Q',
    appId: '1:795386471482:ios:b60303ae8d398f9d05c103',
    messagingSenderId: '795386471482',
    projectId: 'chat-gemini-5a384',
    storageBucket: 'chat-gemini-5a384.appspot.com',
    iosBundleId: 'com.nograve.chatGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFn67MvLxSooOVajwhlgia-faT6xh6x7Q',
    appId: '1:795386471482:ios:b60303ae8d398f9d05c103',
    messagingSenderId: '795386471482',
    projectId: 'chat-gemini-5a384',
    storageBucket: 'chat-gemini-5a384.appspot.com',
    iosBundleId: 'com.nograve.chatGemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeWHDxXY4vHvlQ2Rx5BgiHKP74BBuNN4U',
    appId: '1:795386471482:web:3b3c542cd85cf7e805c103',
    messagingSenderId: '795386471482',
    projectId: 'chat-gemini-5a384',
    authDomain: 'chat-gemini-5a384.firebaseapp.com',
    storageBucket: 'chat-gemini-5a384.appspot.com',
    measurementId: 'G-8F2XWZ8BBY',
  );
}
